services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      - default

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - 6333:6333
    environment:
      QDRANT__SERVICE__API_KEY: 2b74305e-caa1-4425-ad87-d5982b9b919d
  qdrant-mcp:
    build: ./backend/app/tools/mcp-server-qdrant
    env_file:
      - ./backend/.env
    ports:
      - '8000:8000'
    environment:
      - RUST_LOG=info
      